### ISSUE TITLE
Travis CI setup

### ISSUE THREAD

**Issue by ghost** [cloudtools/atc53#1]
Of bb0696ff91 I have comitted the required .travis.yml, but now need to work out how to enable the repo within Travis itself. Looking at it so far, I can do so for repositories under my username, but the process for an organisation repo appears unclear.

**Comment by markpeek** [comment]
I believe you need to go into the atc53 repo Settings > Integrations & services > Add service. Add Travis and your Travis token.

**Comment by ghost** [comment]
Thanks @markpeek!

Travis [is now setup](https://travis-ci.org/cloudtools/atc53), and the job appears to pass.
